name: CI Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Java 21
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install virtual display (Xvfb)
        run: sudo apt-get install -y xvfb

      - name: Build project
        run: mvn compile --no-transfer-progress

      - name: Run tests
        run: xvfb-run --auto-servernum mvn test --no-transfer-progress
        env:
          DISPLAY: ':99'
          JAVA_TOOL_OPTIONS: >
            --add-opens=javafx.graphics/javafx.scene.text=ALL-UNNAMED
            --add-exports=javafx.graphics/com.sun.javafx.text=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.javafx.text=ALL-UNNAMED
            --add-exports=javafx.graphics/com.sun.javafx.scene.text=ALL-UNNAMED
            --add-exports=javafx.graphics/com.sun.javafx.scene=ALL-UNNAMED
            --add-exports=javafx.graphics/com.sun.javafx.geom=ALL-UNNAMED
